services:

  backend_django:
    build:
      context: .
    container_name: festperk
    ports:
      - "8000:8000"
    volumes:
      - back_workdir:/app
    networks:
       - festperknet

networks:
  festperknet:
    driver: bridge

volumes:
  back_workdir:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind