services:

  db_postgres:
    image: postgres:alpine3.18
    container_name: database_postgre
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: festperk
    networks:
       - festperknet

  backend_django:
    build:
      context: .
    container_name: festperk
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres
    volumes:
      - back_workdir:/app
    networks:
       - festperknet

networks:
  festperknet:
    driver: bridge

volumes:
  back_workdir:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind